### ISSUE TITLE
Update externs to match Electron 1.0 release

### ISSUE THREAD

**Issue by BigPhilCombo** [tong/hxelectron#17]
Electron has gone 1.0 but their API has changed.  It would be awesome if the externs could get updated to support the revised API.

**Comment by fponticelli** [comment]
Totally ... PRs are very well accepted :)

**Comment by tong** [comment]
We should port the api-demo-app: https://github.com/electron/electron-api-demos too.

**Comment by fponticelli** [comment]
That's a great idea, maybe worth splitting the issues?

**Comment by BigPhilCombo** [comment]
I'm not opposed to doing some externs but it will have to wait until I have
a project at the workplace that requires it, that could be within the next
month.

On Wed, May 11, 2016 at 5:57 PM, Franco Ponticelli <notifications@github.com

> wrote:
> 
> That's a great idea, maybe worth splitting the issues?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fponticelli/hxelectron/issues/17#issuecomment-218602709

## 

Phillip Chertok

**Comment by BigPhilCombo** [comment]
So I started working on this and I have run into a dilemma.  In certain scenarios you need different @jsRequire calls and I don't know how to handle it.

For example if you need to access a browser window from the main process you need the following metadata

@:jsRequire("electron", "BrowserWindow")

but if you need the Browser Window in a render process you need the following;

@:jsRequire("electron", "remote.BrowserWindow")

Any thoughts on how to handle it?

**Comment by tong** [comment]
How about a compiler flag?

``` haxe
#if electron_main
@:jsRequire("electron", "BrowserWindow")
#elseif electron_renderer
@:jsRequire("electron", "remote.BrowserWindow")
#end
```

**Comment by fponticelli** [comment]
We could cheat and do something like this:

``` haxe
@:jsRequire("electron", "BrowserWindow || require('elecron').remote.BrowserWindow")
```

NOT TESTED!

**Comment by BigPhilCombo** [comment]
Someone in IRC suggested making a base class with fields and without
@:jsRequire's and then two extending classes that have @:jsRequire.  I like
this idea a bit more than the previous 2 suggested solutions but it's still
not optimal.

On Thu, May 12, 2016 at 11:58 AM, Franco Ponticelli <
notifications@github.com> wrote:

> We could cheat and do something like this:
> 
> @:jsRequire("electron", "BrowserWindow || require('elecron').remote. BrowserWindow")
> 
> NOT TESTED!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fponticelli/hxelectron/issues/17#issuecomment-218802689

## 

Phillip Chertok

**Comment by fponticelli** [comment]
It is clean but I don't like much the artificial class inheritance. Maybe we could try that and add a macro magic to remove the parent class?

**Comment by tong** [comment]
At some point there sould be a json file describing the api we can use to generate the extern types (electron/electron#3375). But, like with atom-api.json, these descriptions do not describe everything, so we would end up with a lot of Dynamic (correct me if i am wrong).

If we want to depend on this i think we still should create full typed externs by hand (as we already have for <1.0) and use the description file, as soon as it's available, to validate them.

**Comment by zeke** [comment]
Work in progress: https://github.com/electron/electron/pull/6408

**Comment by ousado** [comment]
What's the state of this? Does someone have a WIP in a branch somewhere?

**Comment by tong** [comment]
Here https://github.com/tong/hxelectron/tree/generate-externs is a initial version which auto generates the externs (currently electron 1.4.3). Not heavily tested, but the docs are building and the demo app is working.

**Comment by fponticelli** [comment]
That's great, are there plans to integrate the generated stuff with hand curated type? I see quite a few Dynamics here and there that could be replaced.

**Comment by tong** [comment]
I've already added some improvements and think it should be possible to rely on generated externs only.
There are some glitches cause of invalid documentation, namely:
- Types of instance properties seem to be missing from api description (electron/electron/issues/7774).
- There is a `electron.Any` type which comes from invalid description as it should be an Object (electron/electron/pull/7682).
- The `electron.Accelerator` description is missing
- The `electron.App` type is manually patched with a static `on()` method.

To distinguish between types available in main and/or renderer process i 've added `@:require(electron_main)` and `@:require(electron_renderer)` meta data. I am not sure if that's cool with `--display`, needs test.

**Comment by ousado** [comment]
@tong awesome!
