### ISSUE TITLE
Is there a simple way to package?

### ISSUE THREAD

**Issue by Justinfront** [tong/hxelectron#26]
Really nice :)
Only have short time to rebuild something via this approach for kiosk video app, but not sure on creating a version to show designers.  Any guidence welcome.

**Comment by Justinfront** [comment]
**Package Instruction Guide**

_( instructions are from mac users perspective slight variations may apply for linux/win users. )_

To package an electron application you will require getting a tool via terminal 

>`> npm install electron-packager -g`

For packaging electron applications all relevant files need to be in a single folder, hxElectron is not quite setup ideally for that so we can create an hxml file, for simplicity I will assume all your assets are in an **"asset"** folder within your **'demo'** folder and all other aspects are as per the hxElectron demo.
1) First lets make the dev process a bit simpler by creating a **"compile.hxml"** file.
```
-cmd npm run build
--next
-cmd npm start
```
This us allows us to run the dev will less effort.
>`> haxe compile.hxml`
2) We need to move all files into a **'build'** folder which the packager will use to create our packages with. We can create a simple **'compileApp.hxml'** for this, we can also run the packager, the name of the demo app if you look inside the current package.json is **'hxelectron-demo'** so we use that name in our package script.
```
# rebuild the app prior to packaging.
-cmd npm run build
--next
# remove old build folder if exists and create an empty one.
-cmd rm -r -f build
-cmd mkdir build
# these are generated
-cmd cp app.js build/app.js
-cmd cp main.js build/main.js
# this is your main html file.
-cmd cp app.html build/app.html
# assets is an additional folder where you might put videos and images etc..
-cmd cp -r assets build/assets
# this is the important file it defines the project properties.
-cmd cp package.json build/package.json
# build for your system
-cmd electron-packager build hxelectron-demo .
# build all - remove hash to enable.
# -cmd electron-packager build hxelectron-demo --platform=all
```
>`> haxe compileApp.hxml`

3) if your running on mac and you want to build a windows version you will need wine which if you are using brew can be installed easily but seem to take awhile, and along with linux can be installed by using the --platform==all flag.
For just compiling mac you can use **'.'** or --platform==darwin, or --platform==mas  for iphone store, --arch allows you to define 32 or 64 see documentation.  
So to allow windows build on a mac.
>`> brew cast install xquartz`
>`> brew install wine`

Once you have wine, you can try compiling all...

>`> electron-packager build hxelectron-demo --platform=all`

it then seems to want to install gecko ... which you ok.
I am not sure how effective it is creating an app for a different platform, it's probably ideal to compile on the platform you require, and certainly mac signing normally needs to be done on a mac see the electron-packager github for more info.

see the [electron-packager](https://github.com/electron-userland/electron-packager) github for more information.

_Perhaps this quick tutorial can be ebellished as an additional readme on hxElectron?_

**Comment by tong** [comment]
I think this is out of context for this project.
Packaging an electron application does not change using hx→js and is already well documented in fe electron-packager.

**Comment by Justinfront** [comment]
Extended Franco's hxelectron code to include packaging quite a long time back, I will leave a link here incase it's useful to people who don't want to read javascript packaging instructions and just want a quick up and running test, may need updates for latest Haxe / Electron, as I have not used it lately but worked on pc/mac when I last tried.
https://github.com/nanjizal/nanjizalOnElectron
Feel free to integrate anything useful in this or other projects, while you maybe happy to read documentions I like to get something working and then just use that next time I need it so I can concentrate on code not setups.

**Comment by tong** [comment]
Thanks for the information.
