### ISSUE TITLE
Dialog.showOpenDialog is undefined

### ISSUE THREAD

**Issue by gmisail** [tong/hxelectron#32]
The error thrown in the Javascript console:
`Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined`

Source:
```
Dialog.showOpenDialog(Remote.getCurrentWindow(), {}, function(d){
            trace(d);
});
```

Is it possible that I am using it incorrectly? I am trying to port it over from my original Javascript source as well as I can. This has been the only issue so far regarding the externs.

**Comment by tong** [comment]
`electron.renderer.Remote` is not available in the main process so i am wondering why this works in your original version.

**Comment by gmisail64** [comment]
I am running this on the client side. Even without the Rempte calls I still
get the same issue.

**Comment by gmisail** [comment]
I am executing the code on the client side. Am I using this incorrectly? In my original main.js (loaded by HTML), I have something around the lines of:

```
const electron = require('electron').remote
const dialog = electron.dialog

dialog.showOpenDialog((fileNames) => {
       //more code that doesn't matter...
})
```

In the Haxe equivalent, I have the above code which gives me the error that Dialog is undefined.

**Comment by tong** [comment]
If your js is loaded from the html you are in the `renderer` process.
This sould work:
```haxe
js.Lib.require('electron').remote.dialog.showOpenDialog( electron.renderer.Remote.getCurrentWindow(), {}, function(d){
  trace(d);
});
```
See: https://github.com/electron/electron/blob/master/docs/api/dialog.md

**Comment by gmisail** [comment]
All good, thank you so much.

**Comment by habibieamrullah** [comment]
> If your js is loaded from the html you are in the `renderer` process. This sould work:
> 
> ```hx
> js.Lib.require('electron').remote.dialog.showOpenDialog( electron.renderer.Remote.getCurrentWindow(), {}, function(d){
>   trace(d);
> });
> ```
> 
> See: https://github.com/electron/electron/blob/master/docs/api/dialog.md

when I tried this code now it says js is not defined.
