### ISSUE TITLE
Using Http class in Renderer throws error because of inclusion of Hxnodejs

### ISSUE THREAD

**Issue by BigPhilCombo** [tong/hxelectron#38]
When using a simple Http loader to load a text file in the renderer context, Electron will throw an error when including the electron externs. This is because -D nodejs changes the behavior on the Http class.

See the issue here:

https://github.com/massiveinteractive/mloader/issues/27

**Comment by tong** [comment]
For me it works fine, no errors.
Using: hxelectron v2.0.7-beta.1, electron 2.0.7, haxe 4.0.0-preview.4, hxnodejs 4.0.9
