### ISSUE TITLE
Cannot use `App.commandLine` static reference

### ISSUE THREAD

**Issue by jgranick** [tong/hxelectron#39]
The `App.commandLine` field appears to be static in the original library, for setting command-line launch arguments before the App is ready. Should it (or other?) fields be changed to static in the externs?

**Comment by tong** [comment]
Right, should be static.
This bug affects `commandLine` and `dock` in `App` and probably  also fields in other classes.

**Comment by tong** [comment]
Should be fixed, but needs testing as i've switched to a pure macro based api generator.

**Comment by hoseyjoe** [comment]
Appears fixed in 2.0.9
