### ISSUE TITLE
Touch bar items missing

### ISSUE THREAD

**Issue by kevinresol** [tong/hxelectron#40]
They are fields of `TouchBar`, so the code would be like:

```haxe
@:jsRequire('electron', 'TouchBar.TouchBarButton')
extern class TouchBarButton {}
```

List of the items could be found in the docs: https://electronjs.org/docs/api/touch-bar

**Comment by tong** [comment]
This is an known issue: https://github.com/tong/hxelectron/blob/740602b72cb3d9cf6290c4d8828f9cab614fd7c8/ElectronAPI.hx#L122
https://github.com/tong/hxelectron/blob/740602b72cb3d9cf6290c4d8828f9cab614fd7c8/ElectronAPI.hx#L335

TouchBar types are the only occurence of inline defined types in electron-api.json and not implemented by the generator so far.

**Comment by tong** [comment]
Should be fixed.
