### ISSUE TITLE
Can't access App class (undefined)

### ISSUE THREAD

**Issue by TomByrne** [tong/hxelectron#41]
The demo works for for me, but when I access Electron APIs (instead of just Node ones) I get errors.
For example if I use `electron.main.App.getPath('documents')`, the App class is undefined.

In DevTools, I have found that using this JS does work:
`require('electron').remote.app.getPath('documents')`

In using:
Haxe 4.0.0 preview 5
Node 10.2
Electron 3.0.10
Windows 64

**Comment by tong** [comment]
You cannot access apis in electron.main from the renderer process.
See: https://electronjs.org/docs/tutorial/application-architecture

**Comment by TomByrne** [comment]
Ok, I understand this more now.
One thing I don't really know is how to use the Remote class to access static parts of the main process API (App.getPath for example).
I know this isn't 'recommended' as it causes synchronous comms between processes, but it'd be good to know if there was a way.

At the moment I have to make the App object dynamic (also, the 'getBuiltin' method doesn't seem to exist in the Remote extern)
```
var app:Dynamic = untyped Remote.getBuiltin('app');
var documentsDir = app.getPath('documents');
```
(As this is only done once during app boot I'm not too concerned about the process lockup).

**Comment by tong** [comment]
I've seen the Remote.getBuiltin method but it's not defined in electron-api.json therefore might get removed (?). For such simple communication i guess it's ok to just:
```haxe
var documentsDir = untyped electron.renderer.Remote.app.getPath("documents");
```
For more complex i would use https://electronjs.org/docs/api/ipc-renderer.
