### ISSUE TITLE
Unable to create new BrowserWindow

### ISSUE THREAD

**Issue by 01010111** [tong/hxelectron#42]
I'm trying to create a new (second) window using `new BrowserWindow( { width: 400, height: 400 } );` but I'm getting an error:
```
Uncaught TypeError: electron_main_BrowserWindow is not a constructor
```
Trying to find answers online, people suggest using `electron.remote.BrowserWindow` which doesn't exist in this library. Do I need to go about this differently?

**Comment by tong** [comment]
Have you tried `js.Browser.window.open("another.html");`

**Comment by 01010111** [comment]
I guess that would work, but I think I'd miss out on a lot of features like setting the size, opening it as a modal window, etc.

**Comment by 01010111** [comment]
btw - able to make it work by going into the compiled js and changing
```var electron_main_BrowserWindow = require("electron").BrowserWindow;```
to
```var electron_main_BrowserWindow = require("electron").remote.BrowserWindow;```

**Comment by tong** [comment]
```haxe
var win : electron.main.BrowserWindow = Type.createInstance( js.Lib.require('electron').remote.BrowserWindow, [{ width: 400, height: 400 }] );
```
… should work.

**Comment by 01010111** [comment]
Cool, thanks!
