### ISSUE TITLE
openfl test electron error /usr/local/lib/haxe/lib/electron/4,0,0/src/electron/main/App.hx:331: characters 49-50 : Unexpected ,

### ISSUE THREAD

**Issue by boltomli** [tong/hxelectron#43]
There's no obvious issue in the line.

var quit : electron.main.AppEvent<(js.html.Event, Int) -> Void> = "quit";

**Comment by tong** [comment]
It's a breaking change with haxe4 (HaxeFoundation/haxe-evolution/pull/23).
You can try to regenerate the type definitions using another haxe version, though some (afair minor) changes to hxelectron/ElectronAPI.hx are required.

**Comment by tong** [comment]
… Or upgrade to haxe 4 ;)

**Comment by tong** [comment]
e89fa756affd683fa1cbe6f501510b60a4df5f87 should now be compatible with haxe 3.4.7.
Only thing missing is the documentation for types.

You have to (re)generate the type definitions with `cd hxelectron && haxe api.hxml`.
