### ISSUE TITLE
Event not found

### ISSUE THREAD

**Issue by Disar** [tong/hxelectron#5]
When importing BrowserWindow i get:

```
../../hxelectron/src/electron/main/BrowserWindow.hx:7: lines 7-26 : Type not found : Event
```

Am I missing something?

**Comment by fponticelli** [comment]
`Event` is defined in `hxnodejs` so you are maybe missing that into your `hxml`?

**Comment by Disar** [comment]
Looks like im indeed missing some libs.

[Is this the one i need?](https://github.com/HaxeFoundation/hxnodejs)

Any additional libs i need?

Edit:

I already had Haxe JS Kit in my project path.

**Comment by Disar** [comment]
Sorry for the fuss. It seemed like the libs I tried first were messing up everything. Sorry about the false alarm.

**Comment by fponticelli** [comment]
Not a problem ;)
